#pragma once
#include <Windows.h>
#include <math.h>
#define M_PI 3.141592f

#define RESOURCE 23
#define CLEARFRAME 2
#define RUNFRAME 3
#define StartMap 0
#define EndMap 1000
#define Map_Right_Move 1
#define Map_Left_Move -1
enum BITMAP_IMAGE
{
	BITMAP_BACK,
	BITMAP_BACK_DECO,
	BITMAP_BACK_NOMAL,
	BITMAP_BACK_NOMAL2,
	BITMAP_CASH,
	BITMAP_DIE,
	BITMAP_END,
	BITMAP_ENEMY_L,
	BITMAP_ENEMY_L1,
	BITMAP_ENEMY_R,
	BITMAP_ENEMY_R1,
	BITMAP_FRONT,
	BITMAP_FRONT1,
	BITMAP_ICON,
	BITMAP_MITER,
	BITMAP_PLAYER0,
	BITMAP_PLAYER1,
	BITMAP_PLAYER2,
	BITMAP_STAR,
	BITMAP_STAR1,
	BITMAP_STAR2,
	BITMAP_WIN,
	BITMAP_WIN2,
	z_backBlack,

};